name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Start API Server
      #   run: |
      #     git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git
          
      #     /home/runner/work/second-task-api/second-task-api/simbirsoft_sdet_project
      #     mvn clean package
          
      #     nohup java -jar target/simbirsoft_sdet_project-*.jar &
          
      #     echo "Ожидаем запуск сервера..."
      #     timeout 60 bash -c 'while ! nc -z host.docker.internal; do sleep 1; done'
      #     echo "Сервер запущен!"  

      # - name: Build and run tests
      #   run: mvn clean test

      # - name: Install Allure
      #   run: |
      #     sudo apt-get update
      #     wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure_2.24.0-1_all.deb
      #     sudo dpkg -i allure_2.24.0-1_all.deb
