name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Start API Server
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git
          cd simbirsoft_sdet_project
          mvn clean package -DskipTests
          
          nohup java -jar target/simbirsoft_sdet_project-*.jar &
          
          echo "Waiting for server..."
          timeout 120 bash -c 'while ! curl -s http://localhost:8080/actuator/health >/dev/null; do sleep 2; done'
          echo "Server started!"

      - name: Build and run tests
        run: mvn clean test

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install allure

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: |
            target/surefire-reports
            allure-results
          retention-days: 1
