name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start API Server
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git
          cd simbirsoft_sdet_project
          make run
          mvn clean package -DskipTests
          nohup java -jar target/simbirsoft_sdet_project-*.jar &
          timeout 120 bash -c 'while ! curl -s http://localhost:8080/actuator/health >/dev/null; do sleep 2; done'

      - name: Build and run tests
        run: |
          cd $GITHUB_WORKSPACE
          mvn clean test

      - name: Install Allure
        run: |
          sudo apt-get update
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure_2.24.0-1_all.deb
          sudo dpkg -i allure_2.24.0-1_all.deb

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
